
#ifndef INCLUDE_HAL_KEYPAD_KEYPAD_PRIVATE_H_
#define INCLUDE_HAL_KEYPAD_KEYPAD_PRIVATE_H_

#define KEYPAD_PRESSED 0
#define FLAG_DOWN 0
#define FLAG_UP   1


#endif /* INCLUDE_HAL_KEYPAD_KEYPAD_PRIVATE_H_ */
